-- MySQL Script generated by MySQL Workbench
-- 05/09/16 12:40:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CoSSMunity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CoSSMunity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CoSSMunity` DEFAULT CHARACTER SET utf8 ;
USE `CoSSMunity` ;

-- -----------------------------------------------------
-- Table `CoSSMunity`.`household`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoSSMunity`.`household` (
  `household_id` INT NOT NULL,
  `username` VARCHAR(63) NOT NULL,
  `email_hash` VARCHAR(127) NULL,
  `residents` INT NULL,
  `house_type` VARCHAR(15) NULL,
  `size` INT NULL,
  `age` YEAR NULL,
  `electric_heating` TINYINT(1) NOT NULL DEFAULT 0,
  `electric_car` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`household_id`),
  UNIQUE INDEX `idUser_UNIQUE` (`household_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CoSSMunity`.`score_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoSSMunity`.`score_type` (
  `score_type_id` INT NOT NULL,
  `score_type_name` VARCHAR(63) NOT NULL,
  PRIMARY KEY (`score_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CoSSMunity`.`achievement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoSSMunity`.`achievement` (
  `achievement_id` INT NOT NULL AUTO_INCREMENT,
  `achievement_name` VARCHAR(63) NOT NULL,
  `description` VARCHAR(255) NULL,
  `achievement_image` VARCHAR(255) NULL,
  PRIMARY KEY (`achievement_id`),
  UNIQUE INDEX `AchivementID_UNIQUE` (`achievement_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`achievement_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CoSSMunity`.`household_achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoSSMunity`.`household_achievements` (
  `household_household_id` INT NOT NULL,
  `achievement_achievement_id` INT NOT NULL,
  `achieved` TINYINT(1) NOT NULL DEFAULT 0,
  `date_achieved` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`household_household_id`, `achievement_achievement_id`),
  INDEX `fk_household_achievement_achievement1_idx` (`achievement_achievement_id` ASC),
  CONSTRAINT `fk_household_achievement_household`
    FOREIGN KEY (`household_household_id`)
    REFERENCES `CoSSMunity`.`household` (`household_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_household_achievement_achievement1`
    FOREIGN KEY (`achievement_achievement_id`)
    REFERENCES `CoSSMunity`.`achievement` (`achievement_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CoSSMunity`.`household_scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoSSMunity`.`household_scores` (
  `household_household_id` INT NOT NULL,
  `score_type_score_type_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`household_household_id`, `score_type_score_type_id`, `date`),
  INDEX `fk_household_score_score_type1_idx` (`score_type_score_type_id` ASC),
  CONSTRAINT `fk_household_score_household1`
    FOREIGN KEY (`household_household_id`)
    REFERENCES `CoSSMunity`.`household` (`household_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_household_score_score_type1`
    FOREIGN KEY (`score_type_score_type_id`)
    REFERENCES `CoSSMunity`.`score_type` (`score_type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CoSSMunity`.`rank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoSSMunity`.`rank` (
  `rank_id` INT NOT NULL AUTO_INCREMENT,
  `rank_name` VARCHAR(63) NOT NULL,
  `requirement` INT NOT NULL,
  `rank_image` VARCHAR(255) NULL,
  PRIMARY KEY (`rank_id`),
  UNIQUE INDEX `rank_id_UNIQUE` (`rank_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CoSSMunity`.`household_ranks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoSSMunity`.`household_ranks` (
  `household_household_id` INT NOT NULL,
  `rank_rank_id` INT NOT NULL,
  `date_obtained` DATE NULL,
  PRIMARY KEY (`household_household_id`, `rank_rank_id`),
  INDEX `fk_household_ranks_rank1_idx` (`rank_rank_id` ASC),
  CONSTRAINT `fk_household_ranks_household1`
    FOREIGN KEY (`household_household_id`)
    REFERENCES `CoSSMunity`.`household` (`household_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_household_ranks_rank1`
    FOREIGN KEY (`rank_rank_id`)
    REFERENCES `CoSSMunity`.`rank` (`rank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
